from pathlib import Path
from docx import Document

src = Path('manuscripts/methodology_ieee_v2.6_revised_simulation_polished.docx')
out = Path('manuscripts/methodology_ieee_v2.6_revised_simulation_polished_ieee.docx')

doc = Document(src)

replacements = {
    # Section III.A flow
    'By separating the robotic actuator from the patient\'s limb, the acrylic interface substantially reduces the risk of blunt impact, excessive traction, and crushing injuries that may arise in direct-contact rehabilitation devices. In addition to improving safety, the system has a simple and reproducible structure: it requires only a collaborative robot, a camera, and a permanent magnet, without wearable components, force sensors, or custom actuation modules. The microrobot itself is unpowered and is driven passively by the magnetic field, eliminating the need for onboard electronics or batteries. This hardware simplicity facilitates setup, maintenance, and potential deployment across clinical environments. Moreover, the non-contact actuation mechanism provides an additional safety margin for deploying and refining learning-based controllers on the physical platform.':
    'This physical separation between actuator and patient is central to the system\'s safety design. The acrylic interface substantially reduces the risk of blunt impact, excessive traction, and crushing injuries that may arise in direct-contact rehabilitation devices. In addition to improving safety, the system has a simple and reproducible structure: it requires only a collaborative robot, a camera, and a permanent magnet, without wearable components, force sensors, or custom actuation modules. The microrobot itself is unpowered and is driven passively by the magnetic field, eliminating the need for onboard electronics or batteries. This hardware simplicity facilitates setup, maintenance, and potential deployment across clinical environments, and it provides an additional safety margin that is especially valuable during the iterative development of data-driven controllers.',

    # Section III.B flow and abbreviation definitions
    'We formulate the rehabilitation task as a pursuit-evasion game played on a flat workspace. The patient sits in front of the acrylic surface and uses one hand to chase the magnetic microrobot, which moves under the control of the robot arm below. The goal is to catch the microrobot by bringing the hand within a small contact radius. This is not a static reaching exercise: the microrobot actively evades, so the patient must continuously track, predict, and intercept a moving target, which demands sustained attention and real-time motor planning. Clinical evidence shows that this kind of continuous, goal-directed visuomotor tracking engages the central nervous system and promotes neuroplasticity for motor recovery [X]. To maximize therapeutic benefit, task difficulty must adapt to the patient\'s current ability. This principle is formalized by the Zone of Proximal Development (ZPD), a concept from educational psychology introduced by Vygotsky [X] that describes the range of tasks a learner can perform with guidance but not alone. In our setting, the ZPD translates to a target distance range between the hand and the microrobot: the robot should neither escape completely nor yield passively, but keep the distance within this range so the patient stays challenged without becoming fatigued or frustrated.':
    'We formulate the rehabilitation task as a pursuit-evasion game played on a flat workspace. The patient sits in front of the acrylic surface and uses one hand to chase the magnetic microrobot, which moves under the control of the robot arm below. The goal is to catch the microrobot by bringing the hand within a small contact radius. Unlike static reaching exercises, the microrobot actively evades the patient\'s hand. Catching it therefore requires continuous visuomotor tracking, trajectory prediction, and real-time motor planning--sustained cognitive and physical demands that go beyond point-to-point reaching. Clinical evidence shows that continuous, goal-directed visuomotor tracking engages the central nervous system and promotes neuroplasticity for motor recovery [X]. To maximize therapeutic benefit, task difficulty must adapt to the patient\'s current ability. This need for adaptive difficulty is formalized by the Zone of Proximal Development (ZPD), a concept from educational psychology introduced by Vygotsky [X] that describes the range of tasks a learner can perform with guidance but not alone. In our setting, the ZPD translates to a target distance range between the hand and the microrobot: the robot should neither escape completely nor yield passively, but keep the distance within this range so the patient stays challenged without becoming fatigued or frustrated. Achieving this within the ZPD is non-trivial, as the robot must continuously respond to a patient whose movement speed, strategy, and motor noise may all vary.',

    'Maintaining this therapeutic difficulty range is challenging for conventional control methods. Many classical approaches, such as artificial potential fields or rule-based impedance controllers, rely primarily on hand-crafted rules and instantaneous state feedback. As a result, they may struggle to anticipate higher-level patient strategies, such as trajectory interception, or to adapt to heterogeneous movement patterns across patients. Their performance may further degrade in the presence of neurological motor impairments, including tremor, delayed response, and bradykinesia, because these methods typically lack an explicit mechanism for distinguishing purposeful movement from involuntary perturbations. Reinforcement learning provides a suitable framework for addressing these challenges. In our formulation, the robot learns an evasion policy through repeated interaction with the patient or patient models. The policy is rewarded for maintaining the hand-microrobot distance within the therapeutic range and penalized for unsafe or uninformative behaviors, such as escaping too far or being caught too easily. By conditioning the policy on temporal observations of hand and microrobot motion, the controller can infer patient intent from movement history rather than responding only to instantaneous position error. Through this process, the robot can progressively adapt its behavior to different patient capabilities and maintain an appropriate level of challenge. The following sections describe how the policy is trained to generalize across diverse movement patterns observed in neurological rehabilitation.':
    'Maintaining this therapeutic difficulty range is challenging for conventional control methods. Many classical approaches, such as artificial potential fields or rule-based impedance controllers, rely primarily on hand-crafted rules and instantaneous state feedback. As a result, they may struggle to anticipate higher-level patient strategies, such as trajectory interception, or to adapt to heterogeneous movement patterns across patients. Their performance may further degrade in the presence of neurological motor impairments, including tremor, delayed response, and bradykinesia, because these methods typically lack an explicit mechanism for distinguishing purposeful movement from involuntary perturbations. Reinforcement learning (RL) provides a suitable framework for addressing these challenges. In our formulation, the robot learns an evasion policy through repeated interaction with the patient or patient models. The policy is rewarded for maintaining the hand-microrobot distance within the therapeutic range and penalized for unsafe or uninformative behaviors, such as escaping too far or being caught too easily. By conditioning the policy on temporal observations of hand and microrobot motion, the controller can infer patient intent from movement history rather than responding only to instantaneous position error. Through this process, the robot can progressively adapt its behavior to different patient capabilities and maintain an appropriate level of challenge. The design choices in Section IV--domain randomization, temporal encoding, and league training--are each motivated by a specific challenge identified in this problem formulation.',

    # Methodology intro
    'The previous section formulated the rehabilitation task and motivated the use of reinforcement learning. This section describes the complete training framework. We first introduce a domain randomization scheme that accounts for both patient movement strategies and motor limitations (Section IV-A). We then present a dual-stream encoder with an auxiliary forward dynamics head to extract motion information from noisy temporal observations (Section IV-B). Finally, we describe a league training procedure that improves the robustness of the robot policy against a growing pool of hand behaviors (Section IV-C).':
    'The previous section formulated the rehabilitation task and motivated the use of reinforcement learning. This section describes the complete training framework. We first introduce Cognitive-Motor Decoupled Domain Randomization (CMD-DR), a domain-randomization scheme that accounts for both patient movement strategies and motor limitations (Section IV-A). We then present a dual-stream encoder with an auxiliary future-dynamics head to extract motion information from noisy temporal observations (Section IV-B). Finally, we describe a league training procedure designed to improve the robustness of the robot policy against a growing pool of hand behaviors (Section IV-C).',

    # CMD-DR opening and equations
    'The pursuit-evasion task is implemented as a Gymnasium environment with two interacting entities. The robot policy controls the magnetic microrobot, while the hand represents the patient and is controlled by a separate policy or scripted controller. A key challenge for real-world deployment is that neurological patients may move in very different ways. If the simulated hand follows only one fixed strategy, the learned robot policy may overfit to that behavior and perform poorly when facing real patients. To address this issue, we use a two-layer domain randomization scheme. The first layer randomizes the hand\'s movement strategy. At the beginning of each episode, a hand controller is sampled from an opponent pool. This pool includes simple scripted controllers based on fixed pursuit rules as well as trained RL controllers that can intercept and anticipate the microrobot. The selected controller produces a desired hand displacement at each timestep. The second layer modifies this desired displacement according to motor and sensing constraints. The raw displacement is first passed through a first-order low-pass filter to model muscle inertia:':
    'A key challenge for training a generalizable robot policy is that neurological patients may vary substantially in both movement strategy and motor execution quality. To address this issue, CMD-DR uses a two-layer domain randomization scheme. The first layer randomizes the hand\'s movement strategy. At the beginning of each episode, a hand controller is sampled from an opponent pool. This pool includes simple scripted controllers based on fixed pursuit rules as well as trained RL controllers that can intercept and anticipate the microrobot. The selected controller produces a desired hand displacement at each timestep. The second layer modifies this desired displacement according to motor and sensing constraints. The raw displacement is first passed through a first-order low-pass filter to model muscle inertia:',
    'x_t = alpha x_{t-1} + (1 - alpha) u_t,   alpha in (0, 1),':
    'x_t = alpha x_{t-1} + (1 - alpha) u_t,   alpha in (0, 1).     (1)',
    'Delta x_t = clip(x_t - x_{t-1}, -a_max, a_max).':
    'Delta x_t = clip(x_t - x_{t-1}, -a_max, a_max).     (2)',
    'Gaussian observation noise is further added to simulate position estimation errors from the vision system. To model delayed motor response, a temporal delay is introduced so that the displacement executed at time t corresponds to the intended displacement generated several frames earlier. The delay is sampled at the beginning of each episode. This design separates what the hand attempts to do from how the movement is actually executed. As a result, the robot policy is exposed to a wide range of patient-like behaviors and is encouraged to learn motion patterns that are not tied to a single simulated hand model.':
    'Gaussian observation noise is further added to simulate position estimation errors from the vision system. To model delayed motor response, a temporal delay is introduced so that the displacement executed at time t corresponds to the intended displacement generated several frames earlier. The delay is sampled at the beginning of each episode. Table I lists the parameter values and sampled ranges for the motor-execution constraints. This design separates what the hand attempts to do from how the movement is actually executed. As a result, the robot policy is exposed to a wide range of patient-like behaviors and is encouraged to learn motion patterns that are not tied to a single simulated hand model.',
    'Parameter': 'TABLE I: CMD-DR MOTOR RANDOMIZATION PARAMETERS\nParameter',

    # Encoder abbreviations and equations
    'At each timestep, the 44-dimensional observation vector is divided into a 12-dimensional scalar vector and a 32-dimensional temporal buffer:':
    'To separate geometric context from motion history, the observation vector is split into two streams. At each timestep, the 44-dimensional observation vector is divided into a 12-dimensional scalar vector and a 32-dimensional temporal buffer:',
    'o_t = [s_t ; h_{t-T:t}].':
    'o_t = [s_t ; h_{t-T:t}].     (3)',
    's_t = [p_R; p_H; d(R,H); b_N, b_S, b_E, b_W; stride; a_{t-1}],':
    's_t = [p_R; p_H; d(R,H); b_N, b_S, b_E, b_W; stride; a_{t-1}].     (4)',
    'The temporal buffer h_{t-T:t} contains the T = 16 most recent relative hand displacement vectors, forming a 32-dimensional sequence. This buffer captures recent velocity, acceleration, and repeated movement patterns that cannot be obtained from the current position alone. The scalar vector is processed by an MLP to extract the current geometric information. In parallel, the temporal buffer is processed by a GRU sequence encoder. Because the GRU uses relative displacements rather than absolute positions, it focuses on movement direction, speed, acceleration, and oscillation. The outputs of the two streams are then concatenated and passed through a fusion MLP to produce a shared representation for policy and value prediction.':
    'The temporal buffer h_{t-T:t} contains the T = 16 most recent relative hand displacement vectors, forming a 32-dimensional sequence. This buffer captures recent velocity, acceleration, and repeated movement patterns that cannot be obtained from the current position alone. The scalar vector is processed by a Multi-Layer Perceptron (MLP) to extract the current geometric information. In parallel, the temporal buffer is processed by a Gated Recurrent Unit (GRU) sequence encoder. Because the GRU uses relative displacements rather than absolute positions, it focuses on movement direction, speed, acceleration, and oscillation. The outputs of the two streams are then concatenated and passed through a fusion MLP to produce a shared representation for policy and value prediction.',
    'L_traj = E[||D_hat_{t+1:t+H} - D_{t+1:t+H}||_2^2],   H = 8,':
    'L_traj = E[||D_hat_{t+1:t+H} - D_{t+1:t+H}||_2^2],   H = 8.     (5)',
    'L_total = L_PPO + lambda_traj L_traj + lambda_risk L_risk,':
    'L_total = L_PPO + lambda_traj L_traj + lambda_risk L_risk.     (6)',

    # League training wording and formula
    'A natural baseline is to train the robot and hand policies at the same time. However, simultaneous training in a two-agent game creates a non-stationary learning problem. The return of each agent depends on the policy of the other agent. When both policies are updated together, each update changes the environment faced by the other policy, which conflicts with the stationarity assumption of PPO. In practice, this can lead to cyclic adaptation: the robot learns to exploit the current hand policy, the hand then adapts to the robot, and the robot may forget strategies that were useful against earlier hand behaviors. To avoid this issue, we freeze one side of the interaction while training the other. During robot training, the hand policies are fixed and treated as part of the environment. During hand training, the robot policy is fixed. This alternating procedure provides a more stable learning objective than updating both policies simultaneously.':
    'A straightforward baseline approach is simultaneous training of both policies. However, simultaneous training in a two-agent game creates a non-stationary learning problem. The return of each agent depends on the policy of the other agent. When both policies are updated together, each update changes the environment faced by the other policy, which conflicts with the stationarity assumption of Proximal Policy Optimization (PPO). In practice, this can lead to cyclic adaptation: the robot learns to exploit the current hand policy, the hand then adapts to the robot, and the robot may forget strategies that were useful against earlier hand behaviors. To avoid this issue, one side of the interaction is frozen while the other is trained. During robot training, the hand policies are fixed and treated as part of the environment. During hand training, the robot policy is fixed. This alternating procedure provides a more stable learning objective than updating both policies simultaneously.',
    'Our goal is different from purely competitive games. In rehabilitation, the robot should not simply learn to defeat the hand. Instead, it should maintain an appropriate level of challenge for patients with different movement abilities. A single hand policy cannot represent this range of behavior. We therefore maintain an opponent pool P that stores hand policies from different training stages. These hand policies provide a diverse set of pursuit behaviors for training the robot.':
    'Classic multi-agent RL methods for competitive games often train both sides to maximize cumulative win rate. Our objective, however, differs from purely competitive games. In rehabilitation, the robot should not simply learn to defeat the hand. Instead, it should maintain an appropriate level of challenge for patients with different movement abilities. A single hand policy cannot represent this range of behavior. We therefore maintain an opponent pool P that stores hand policies from different training stages. These hand policies provide a diverse set of pursuit behaviors for training the robot.',
    'As summarized in Algorithm 1, each iteration has two phases. In the robot phase, the opponent pool P is fixed, and the robot policy is trained with PPO against hand policies sampled from the pool. In the hand phase, a new hand policy is initialized from the previous hand policy and further trained against the current fixed robot policy. The trained hand policy is then added to P, increasing the diversity of hand behaviors used in the next robot training phase.':
    'The full procedure is formalized in Algorithm 1. Each iteration has two phases. In the robot phase, the opponent pool P is fixed, and the robot policy is trained with PPO against hand policies sampled from the pool. In the hand phase, a new hand policy is initialized from the previous hand policy and further trained against the current fixed robot policy. The trained hand policy is then added to P, increasing the diversity of hand behaviors used in the next robot training phase.',
    'P(i) propto f(w_i),  f(w) = 1 / (1 + exp(-k * (eta - |w - 0.5|)))':
    'P(i) propto f(w_i),  f(w) = 1 / (1 + exp(-k * (eta - |w - 0.5|))).     (7)',
    'where w_i denotes the normalized episode length against opponent i, k controls the sharpness of the distribution, and eta defines the tolerance band around the target value of 0.5. This sampling rule gives higher probability to hand policies that produce intermediate episode lengths. In this way, the robot is trained more often against opponents that match its current ability, without manually specifying a difficulty schedule.':
    'where w_i denotes the normalized episode length against opponent i, k controls the sharpness of the distribution, and eta defines the tolerance band around the target value of 0.5. This sampling rule gives higher probability to hand policies that produce intermediate episode lengths. In this way, training effort is automatically concentrated on the most informative opponents without requiring a manually specified curriculum.',

    # Results flow refinements
    'The simulation study is organized around the main sources of uncertainty that the controller must handle before physical deployment. We first examine whether iterative league training produces a robot policy that remains effective across a growing set of learned hand behaviors. We then isolate the role of temporal interaction history and auxiliary future-dynamics supervision through a controlled network ablation. Finally, we compare representative robot policies under two automated hand-control mechanisms to assess whether the learned behavior is tied to a single opponent type or transfers across different pursuit strategies.':
    'The simulation study is organized around the main sources of uncertainty that the controller must handle before physical deployment. We first examine whether iterative league training produces a robot policy that remains effective across a growing set of learned hand behaviors. We then isolate the role of temporal interaction history and auxiliary future-dynamics supervision through a controlled network ablation. Finally, we compare representative robot policies under two automated hand-control mechanisms to assess generalization across pursuit strategies.',
    'The league experiment uses a ZPD band of 3.5-5.5 workspace units and trains ten robot generations without providing an explicit opponent identity. The absence of opponent identity makes the task more representative of rehabilitation, where the controller must infer patient capability from motion history rather than from a predefined label. Each robot generation is evaluated against the learned hand pool and a scripted pursuit controller. Time-in-zone (TIS), defined as the fraction of interaction time spent inside the ZPD band, is used as the main robustness metric, with both mean and worst-case values reported to capture average performance and lower-tail robustness.':
    'The league experiment uses a ZPD band of 3.5-5.5 workspace units and trains ten robot generations without providing an explicit opponent identity. Opponent identity is withheld to reflect the real-world condition in which patient capability cannot be directly observed. Each robot generation is evaluated against the learned hand pool and a scripted pursuit controller. Time-In-Zone (TIS), defined as the fraction of interaction time spent inside the ZPD band, is used as the main robustness metric. Mean and worst-case TIS are both reported, since a controller that excels on average may still fail for patients with atypical movement patterns.',
    'The auxiliary prediction panels clarify why this component is still useful. Even when the policy-level improvement is modest, the future-dynamics head exposes what the temporal representation has learned about hand motion. The predicted trajectories capture short-horizon movement direction and progressively diverge at longer horizons, which is consistent with the uncertainty of multi-step forecasting in an interactive task. Thus, the auxiliary task should be interpreted less as an independent performance booster in this run and more as a mechanism for encouraging and diagnosing patient-dynamics representation.':
    'The auxiliary prediction results provide additional insight into what the temporal representation has learned. Even when the policy-level improvement is modest, the future-dynamics head exposes what the temporal representation has learned about hand motion. The predicted trajectories capture short-horizon movement direction and progressively diverge at longer horizons, which is consistent with the uncertainty of multi-step forecasting in an interactive task. In this run, the auxiliary task does not function as an independent performance booster. Instead, it serves as a mechanism for encouraging and diagnosing patient-dynamics representation.',

    # Sim-to-real flow
    'The physical UR10 deployment is not directly comparable to simulation through a pointwise sim-real gap table, because real human behavior, camera latency, magnetic actuation, and safety constraints are not distribution-matched to virtual hands. We therefore treat sim-to-real validation as a real-world closed-loop feasibility study rather than as a paired simulation benchmark. The implementation uses the same 44-dimensional observation structure as simulation: robot position from RTDE, hand and microrobot positions from the overhead camera, boundary features, previous action, and the displacement-history buffer.':
    'Sim-to-real transfer in this system involves multiple compounding gaps: real hand kinematics, camera latency, and magnetic actuation dynamics are all absent from the virtual training environment. We therefore treat physical deployment as a closed-loop feasibility study rather than a paired benchmark comparison. The implementation uses the same 44-dimensional observation structure as simulation: robot position from Real-Time Data Exchange (RTDE), hand and microrobot positions from the overhead camera, boundary features, previous action, and the displacement-history buffer.',
    'The implementation uses temporal decoupling between perception and control. The camera runs at 10-15 Hz, but the robot needs deterministic commands at a fixed control rate. Running both in one thread would cause jitter: a slow YOLO inference would stall the control loop and freeze the robot. We therefore use two threads connected by a single-element message queue. The vision thread captures frames, runs undistortion and detection, and pushes results to the queue. If the queue is full, the stale result is replaced. The control thread runs at 20 Hz and attempts a non-blocking read each cycle. If a new frame is available, the hand position is updated; otherwise the system falls back to dead reckoning using a low-pass filtered velocity estimate from recent vision updates.':
    'Perception and control run in separate threads to avoid jitter. The camera runs at 10-15 Hz, whereas the robot requires deterministic commands at a fixed control rate. Running both processes in one thread would allow a slow You Only Look Once (YOLO) inference step to stall the control loop. We therefore use two threads connected by a single-element message queue. The vision thread captures frames, runs undistortion and detection, and pushes results to the queue. If the queue is full, the stale result is replaced. The control thread runs at 20 Hz and attempts a non-blocking read each cycle. If a new frame is available, the hand position is updated; otherwise the system falls back to dead reckoning using a low-pass filtered velocity estimate from recent vision updates.',

    # Discussion limitation and conclusion
    'The auxiliary future-prediction task should be viewed as a representation-learning component rather than as a guaranteed source of immediate reward improvement. Its value is that it provides dense supervision on patient motion and makes the learned temporal representation inspectable through predicted trajectories. The current results suggest that the auxiliary signal is directionally useful but not yet optimally coupled to the control objective. Future work should therefore study loss weighting, prediction horizon, and curriculum timing to better translate representation quality into policy improvement.':
    'The auxiliary future-prediction task should be viewed as a representation-learning component rather than as a guaranteed source of immediate reward improvement. Its value is that it provides dense supervision on patient motion and makes the learned temporal representation inspectable through predicted trajectories. The current results suggest that the auxiliary signal improves trajectory representation quality even when policy-level gains are modest. One possible reason is that the auxiliary loss and PPO objective are optimized jointly but not adaptively balanced during training. Future work should therefore study loss weighting, prediction horizon, and curriculum timing to better translate representation quality into policy improvement.\n\nThe study also has limitations. First, the virtual hand models approximate patient behavior but cannot fully capture the variability of real neurological impairments. Second, the ZPD band is defined geometrically in simulation, and its clinical validity must be examined in human studies. Third, the real-world perception pipeline operates at 10-15 Hz, which may be insufficient for very rapid hand movements. These limitations motivate systematic physical validation and human-in-the-loop evaluation before clinical interpretation.',
    'This manuscript presents a simulation-to-real RL framework for adaptive non-contact upper-limb rehabilitation. CMD-DR generates diverse virtual patient behavior by separating intended movement strategy from motor execution constraints. A dual-stream recurrent encoder uses interaction history to infer latent patient dynamics, and an auxiliary future-prediction head supplies dense self-supervised representation learning. Iterative league training improves robustness across learned hand opponents, and the GRU ablation confirms the importance of temporal sequence modeling. The scripted-versus-agent comparison further shows that league training provides more balanced behavior than policies trained against a single opponent type. The next stage is to complete mouse-controlled testing and systematic physical validation on the UR10 magnetic microrobot platform.':
    'This manuscript presents a simulation-to-real RL framework for adaptive non-contact upper-limb rehabilitation. CMD-DR generates diverse virtual patient behavior by separating intended movement strategy from motor execution constraints. A dual-stream recurrent encoder uses interaction history to infer latent patient dynamics, and an auxiliary future-prediction head supplies dense self-supervised representation learning. Iterative league training improves robustness across learned hand opponents, and the GRU ablation confirms the importance of temporal sequence modeling. The scripted-versus-agent comparison further shows that league training provides more balanced behavior than policies trained against a single opponent type. Ongoing work includes mouse-controlled human-in-the-loop trials and systematic physical validation on the UR10 platform, which will constitute the next phase of this research program.'
}

for p in doc.paragraphs:
    text = p.text.strip()
    if text in replacements:
        p.text = replacements[text]

doc.save(out)
print(out.as_posix())
