from pathlib import Path
from shutil import copy2
from docx import Document

src = Path('manuscripts/methodology_ieee_v2.7_no_discussion_conclusion.docx')
out = Path('manuscripts/methodology_ieee_v2.8_academic_style.docx')
copy2(src, out)

doc = Document(out)

replacements = {
    'To reduce the physical risks of rigid rehabilitation robots and provide an engaging therapeutic environment, we introduce a magnetically-actuated non-contact rehabilitation system. This section describes the hardware architecture, states the control problem, and formulates it as a reinforcement learning (RL) task.':
    'We introduce a magnetically actuated, non-contact rehabilitation system designed to reduce the physical risks associated with rigid robotic interaction while preserving an engaging motor-training task. This section first describes the hardware architecture and then formulates the control problem as a reinforcement learning (RL) task.',

    'The platform achieves safety by physically separating the robotic actuator from the patient. As shown in Fig. X, the system has three layers. The actuation layer places a UR10 robotic arm beneath the workspace, with a permanent magnet on its end-effector that drives the microrobot above. The interaction layer is a 5 mm acrylic sheet that supports the unpowered magnetic microrobot while acting as a barrier between the arm and the patient. The perception layer uses an overhead RGB camera connected via USB to a host computer, which also communicates with the UR10 over Ethernet. At each control cycle the computer acquires a camera frame, estimates the positions of the microrobot and the patient\'s hand, and sends target pose commands to the arm.':
    'The platform improves safety by physically separating the robotic actuator from the patient. As shown in Fig. X, the system consists of three layers. The actuation layer places a UR10 robotic arm beneath the workspace, with a permanent magnet mounted on the end-effector to drive the microrobot above. The interaction layer is a 5-mm acrylic sheet that supports the unpowered magnetic microrobot and serves as a barrier between the arm and the patient. The perception layer uses an overhead RGB camera connected to a host computer, which also communicates with the UR10 over Ethernet. At each control cycle, the computer acquires a camera frame, estimates the positions of the microrobot and the patient\'s hand, and sends target pose commands to the arm.',

    'This physical separation between actuator and patient is central to the system\'s safety design. The acrylic interface substantially reduces the risk of blunt impact, excessive traction, and crushing injuries that may arise in direct-contact rehabilitation devices. In addition to improving safety, the system has a simple and reproducible structure: it requires only a collaborative robot, a camera, and a permanent magnet, without wearable components, force sensors, or custom actuation modules. The microrobot itself is unpowered and is driven passively by the magnetic field, eliminating the need for onboard electronics or batteries. This hardware simplicity facilitates setup, maintenance, and potential deployment across clinical environments, and it provides an additional safety margin that is especially valuable during the iterative development of data-driven controllers.':
    'This physical separation is central to the safety design. The acrylic interface reduces the risk of blunt impact, excessive traction, and crushing injuries that may occur in direct-contact rehabilitation devices. The hardware is also simple and reproducible: it requires a collaborative robot, a camera, and a permanent magnet, without wearable components, force sensors, or custom actuation modules. Because the microrobot is unpowered and driven passively by the magnetic field, it does not require onboard electronics or batteries. This simplicity facilitates setup and maintenance, and it provides an additional safety margin during the iterative development of data-driven controllers.',

    'We formulate the rehabilitation task as a pursuit-evasion game played on a flat workspace. The patient sits in front of the acrylic surface and uses one hand to chase the magnetic microrobot, which moves under the control of the robot arm below. The goal is to catch the microrobot by bringing the hand within a small contact radius. Unlike static reaching exercises, the microrobot actively evades the patient\'s hand. Catching it therefore requires continuous visuomotor tracking, trajectory prediction, and real-time motor planning--sustained cognitive and physical demands that go beyond point-to-point reaching. Clinical evidence shows that continuous, goal-directed visuomotor tracking engages the central nervous system and promotes neuroplasticity for motor recovery [X]. To maximize therapeutic benefit, task difficulty must adapt to the patient\'s current ability. This need for adaptive difficulty is formalized by the Zone of Proximal Development (ZPD), a concept from educational psychology introduced by Vygotsky [X] that describes the range of tasks a learner can perform with guidance but not alone. In our setting, the ZPD translates to a target distance range between the hand and the microrobot: the robot should neither escape completely nor yield passively, but keep the distance within this range so the patient stays challenged without becoming fatigued or frustrated. Achieving this within the ZPD is non-trivial, as the robot must continuously respond to a patient whose movement speed, strategy, and motor noise may all vary.':
    'We formulate the rehabilitation task as a pursuit-evasion game on a flat workspace. The patient sits in front of the acrylic surface and uses one hand to chase the magnetic microrobot, which is controlled by the robot arm below. The goal is to bring the hand within a small contact radius of the microrobot. Unlike static reaching exercises, the microrobot actively evades the patient\'s hand, requiring continuous visuomotor tracking, trajectory prediction, and real-time motor planning. Such goal-directed tracking can impose sustained cognitive and physical demands beyond point-to-point reaching and is relevant to motor recovery [X]. To maximize therapeutic benefit, task difficulty must adapt to the patient\'s current ability. We formalize this requirement using the Zone of Proximal Development (ZPD), which describes tasks that remain challenging but achievable with support [X]. In our setting, the ZPD corresponds to a target distance range between the hand and the microrobot. The robot should neither escape completely nor yield passively; instead, it should keep the interaction within this range so that the patient remains engaged without becoming fatigued or frustrated. This objective is challenging because patient movement speed, strategy, delay, and motor noise can vary over time.',

    'Maintaining this therapeutic difficulty range is challenging for conventional control methods. Many classical approaches, such as artificial potential fields or rule-based impedance controllers, rely primarily on hand-crafted rules and instantaneous state feedback. As a result, they may struggle to anticipate higher-level patient strategies, such as trajectory interception, or to adapt to heterogeneous movement patterns across patients. Their performance may further degrade in the presence of neurological motor impairments, including tremor, delayed response, and bradykinesia, because these methods typically lack an explicit mechanism for distinguishing purposeful movement from involuntary perturbations. RL provides a suitable framework for addressing these challenges. In our formulation, the robot learns an evasion policy through repeated interaction with the patient or patient models. The policy is rewarded for maintaining the hand-microrobot distance within the therapeutic range and penalized for unsafe or uninformative behaviors, such as escaping too far or being caught too easily. By conditioning the policy on temporal observations of hand and microrobot motion, the controller can infer patient intent from movement history rather than responding only to instantaneous position error. Through this process, the robot can progressively adapt its behavior to different patient capabilities and maintain an appropriate level of challenge. The design choices in Section IV--domain randomization, temporal encoding, and league training--are each motivated by a specific challenge identified in this problem formulation.':
    'Conventional controllers are not well suited to this setting. Methods based on artificial potential fields or rule-based impedance control usually rely on hand-crafted responses to instantaneous state feedback. They therefore have limited ability to anticipate higher-level patient strategies, such as interception, or to adapt to heterogeneous movement patterns. Their performance may degrade further under tremor, delayed response, or bradykinesia because they do not explicitly distinguish purposeful movement from involuntary perturbations. RL provides a natural framework for learning such adaptive behavior through repeated interaction. In our formulation, the robot learns an evasion policy that is rewarded for keeping the hand-microrobot distance within the therapeutic range and penalized for unsafe or uninformative behavior, such as escaping too far or being caught too easily. By conditioning the policy on temporal observations, the controller can infer patient intent from movement history rather than reacting only to instantaneous position error. The design choices in Section IV--domain randomization, temporal encoding, and league training--address these sources of patient variability.',

    'The previous section formulated the rehabilitation task and motivated the use of reinforcement learning. This section describes the complete training framework. We first introduce Cognitive-Motor Decoupled Domain Randomization (CMD-DR), a domain-randomization scheme that accounts for both patient movement strategies and motor limitations (Section IV-A). We then present a dual-stream encoder with an auxiliary future-dynamics head to extract motion information from noisy temporal observations (Section IV-B). Finally, we describe a league training procedure designed to improve the robustness of the robot policy against a growing pool of hand behaviors (Section IV-C).':
    'This section describes the training framework. We first introduce Cognitive-Motor Decoupled Domain Randomization (CMD-DR), which separates patient movement strategy from motor execution limitations. We then present a dual-stream encoder with an auxiliary future-dynamics head for extracting motion information from noisy temporal observations. Finally, we describe a league-training procedure designed to improve robustness against a growing pool of hand behaviors.',

    'A key challenge for training a generalizable robot policy is that neurological patients may vary substantially in both movement strategy and motor execution quality. To address this issue, CMD-DR uses a two-layer domain randomization scheme. The first layer randomizes the hand\'s movement strategy. At the beginning of each episode, a hand controller is sampled from an opponent pool. This pool includes simple scripted controllers based on fixed pursuit rules as well as trained RL controllers that can intercept and anticipate the microrobot. The selected controller produces a desired hand displacement at each timestep. The second layer modifies this desired displacement according to motor and sensing constraints. The raw displacement is first passed through a first-order low-pass filter to model muscle inertia:':
    'A generalizable robot policy must account for variation in both patient strategy and motor execution. CMD-DR addresses these two factors separately. The first layer randomizes the hand strategy by sampling a controller from an opponent pool at the beginning of each episode. The pool contains scripted pursuit controllers and trained RL controllers that can intercept or anticipate the microrobot. The selected controller produces a desired hand displacement at each timestep. The second layer transforms this desired displacement through motor and sensing constraints. Specifically, the raw displacement is passed through a first-order low-pass filter to model muscle inertia:',

    'Gaussian observation noise is further added to simulate position estimation errors from the vision system. To model delayed motor response, a temporal delay is introduced so that the displacement executed at time t corresponds to the intended displacement generated several frames earlier. The delay is sampled at the beginning of each episode. Table I lists the parameter values and sampled ranges for the motor-execution constraints. This design separates what the hand attempts to do from how the movement is actually executed. As a result, the robot policy is exposed to a wide range of patient-like behaviors and is encouraged to learn motion patterns that are not tied to a single simulated hand model.':
    'Gaussian observation noise simulates position-estimation errors from the vision system. A sampled temporal delay models delayed motor response by executing a displacement generated several frames earlier. Table I lists the parameter values and sampled ranges for these constraints. By separating intended movement from motor execution, CMD-DR exposes the robot policy to diverse patient-like behaviors and reduces dependence on any single simulated hand model.',

    'The patient\'s intended movement cannot be directly inferred from a single frame. In addition, the observed hand motion may be affected by sensing noise, motor delay, tremor-like perturbations, and slow response. Therefore, using only instantaneous position inputs may not be sufficient for the policy to distinguish purposeful movement from short-term disturbances. To address this problem, we design a dual-stream encoder with an auxiliary prediction task, as shown in Fig. X.':
    'A single frame is often insufficient for inferring patient intent. Observed hand motion may reflect sensing noise, motor delay, tremor-like perturbations, or slow response, rather than deliberate pursuit. We therefore use a dual-stream encoder with an auxiliary prediction task, as shown in Fig. X.',

    'To separate geometric context from motion history, the observation vector is split into two streams. At each timestep, the 44-dimensional observation vector is divided into a 12-dimensional scalar vector and a 32-dimensional temporal buffer:':
    'The encoder separates geometric context from motion history. At each timestep, the 44-dimensional observation vector is divided into a 12-dimensional scalar vector and a 32-dimensional temporal buffer:',

    'The temporal buffer h_{t-T:t} contains the T = 16 most recent relative hand displacement vectors, forming a 32-dimensional sequence. This buffer captures recent velocity, acceleration, and repeated movement patterns that cannot be obtained from the current position alone. The scalar vector is processed by a Multi-Layer Perceptron (MLP) to extract the current geometric information. In parallel, the temporal buffer is processed by a Gated Recurrent Unit (GRU) sequence encoder. Because the GRU uses relative displacements rather than absolute positions, it focuses on movement direction, speed, acceleration, and oscillation. The outputs of the two streams are then concatenated and passed through a fusion MLP to produce a shared representation for policy and value prediction.':
    'The temporal buffer h_{t-T:t} contains the T = 16 most recent relative hand displacement vectors, forming a 32-dimensional sequence. This buffer captures velocity, acceleration, and repeated movement patterns that are unavailable from the current position alone. The scalar vector is processed by a Multi-Layer Perceptron (MLP) to extract geometric information. In parallel, the temporal buffer is processed by a Gated Recurrent Unit (GRU) sequence encoder. Because the GRU operates on relative displacements rather than absolute positions, it emphasizes movement direction, speed, acceleration, and oscillation. The two stream outputs are concatenated and passed through a fusion MLP to produce a shared representation for policy and value prediction.',

    'Although the ZPD-based reward provides a continuous training signal, it does not directly teach the encoder how to represent patient motion. Learning this representation only through policy reward can be slow and unstable. To provide a more direct signal, we attach a future-dynamics head to the fused representation. This head predicts the patient\'s future relative displacement over an eight-step horizon and also estimates near-catch risk. Since future displacements are already contained in the rollout, these targets can be obtained without extra data collection or manual annotation. The auxiliary trajectory loss is defined as:':
    'The ZPD-based reward provides a control signal, but it does not directly supervise how the encoder should represent patient motion. Learning this representation only through policy reward can therefore be slow and unstable. To provide a denser signal, we attach a future-dynamics head to the fused representation. This head predicts the patient\'s relative displacement over an eight-step horizon and estimates near-catch risk. Because future displacements are already available from the rollout, the auxiliary targets require no additional annotation. The trajectory loss is defined as:',

    'where lambda_traj and lambda_risk control the auxiliary loss weights. Because the future-dynamics head shares the encoder with the policy, its gradients also update the spatial and temporal streams. This encourages the encoder to capture patient inertia, delay, and interaction dynamics, helping the robot policy anticipate near-future hand motion instead of reacting only to the current hand-microrobot distance.':
    'where lambda_traj and lambda_risk control the auxiliary loss weights. Because the future-dynamics head shares the encoder with the policy, its gradients also update the spatial and temporal streams. This encourages the encoder to capture patient inertia, delay, and interaction dynamics, enabling the policy to anticipate near-future hand motion rather than reacting only to the current hand-microrobot distance.',

    'A straightforward baseline approach is simultaneous training of both policies. However, simultaneous training in a two-agent game creates a non-stationary learning problem. The return of each agent depends on the policy of the other agent. When both policies are updated together, each update changes the environment faced by the other policy, which conflicts with the stationarity assumption of Proximal Policy Optimization (PPO). In practice, this can lead to cyclic adaptation: the robot learns to exploit the current hand policy, the hand then adapts to the robot, and the robot may forget strategies that were useful against earlier hand behaviors. To avoid this issue, one side of the interaction is frozen while the other is trained. During robot training, the hand policies are fixed and treated as part of the environment. During hand training, the robot policy is fixed. This alternating procedure provides a more stable learning objective than updating both policies simultaneously.':
    'Training both policies simultaneously is a straightforward baseline, but it creates a non-stationary learning problem. The return of each agent depends on the policy of the other agent. When both policies are updated together, each update changes the environment faced by the other policy, violating the stationarity assumption of Proximal Policy Optimization (PPO). In practice, this can lead to cyclic adaptation and forgetting: the robot exploits the current hand policy, the hand adapts, and the robot loses strategies that were useful against earlier hands. We avoid this issue by freezing one side of the interaction while training the other. During robot training, the hand policies are fixed and treated as part of the environment. During hand training, the robot policy is fixed.',

    'Classic multi-agent RL methods for competitive games often train both sides to maximize cumulative win rate. Our objective, however, differs from purely competitive games. In rehabilitation, the robot should not simply learn to defeat the hand. Instead, it should maintain an appropriate level of challenge for patients with different movement abilities. A single hand policy cannot represent this range of behavior. We therefore maintain an opponent pool P that stores hand policies from different training stages. These hand policies provide a diverse set of pursuit behaviors for training the robot.':
    'The objective also differs from purely competitive games. In rehabilitation, the robot should not simply learn to defeat the hand. It should maintain an appropriate level of challenge for patients with different movement abilities. A single hand policy cannot represent this range of behavior, so we maintain an opponent pool P containing hand policies from different training stages. This pool provides a diverse set of pursuit behaviors for robot training.',

    'Uniformly sampling from the opponent pool is inefficient. Weak hand policies provide little learning signal because the robot can maintain the desired distance too easily. Very strong hand policies may lead to mostly failed episodes, which also provide limited useful feedback. The most useful hand policies are those that are challenging but not impossible for the current robot policy. To focus training on these useful opponents, we track the robot\'s average normalized episode length against each hand policy and sample opponents using a length-prioritized distribution:':
    'Uniform sampling from the opponent pool is inefficient. Weak hand policies provide little learning signal because the robot can maintain the desired distance too easily, whereas very strong hand policies can terminate episodes before useful feedback is obtained. The most informative opponents are challenging but not impossible for the current robot. We therefore track the robot\'s average normalized episode length against each hand policy and sample opponents using a length-prioritized distribution:',

    'The simulation study is organized around the main sources of uncertainty that the controller must handle before physical deployment. We first examine whether iterative league training produces a robot policy that remains effective across a growing set of learned hand behaviors. We then isolate the role of temporal interaction history and auxiliary future-dynamics supervision through a controlled network ablation. Finally, we compare representative robot policies under two automated hand-control mechanisms to assess generalization across pursuit strategies.':
    'The simulation study targets the main sources of uncertainty that the controller must handle before physical deployment. We first test whether iterative league training yields a robot policy that remains effective across a growing set of learned hand behaviors. We then isolate the role of temporal interaction history and auxiliary future-dynamics supervision through a controlled network ablation. Finally, we compare representative robot policies under two automated hand-control mechanisms to assess generalization across pursuit strategies.',

    'Fig. 1 shows that robustness improves progressively as the opponent pool becomes more diverse. The final-generation robot achieves the strongest overall performance against learned hands, and the improvement is visible not only in the mean TIS curve but also in the worst-case trend. This distinction is important for rehabilitation: a policy that performs well only on average may still fail for patients whose movement patterns are difficult or atypical. The league result therefore suggests that opponent accumulation improves lower-tail performance, rather than merely optimizing for an easy subset of virtual patients.':
    'Fig. 1 shows that robustness improves as the opponent pool becomes more diverse. The final-generation robot achieves the strongest overall performance against learned hands, and the improvement appears in both the mean TIS curve and the worst-case trend. This distinction matters for rehabilitation because a policy that performs well on average may still fail for patients with difficult or atypical movement patterns. The league result therefore suggests that opponent accumulation improves lower-tail performance rather than optimizing for an easy subset of virtual patients.',

    'The sorted empirical matrix provides a complementary view of the same phenomenon. Early robot generations perform well only against a limited portion of the hand pool, whereas later generations maintain useful ZPD interaction across a broader range of opponent difficulty. The scripted-hand evaluation remains useful as a consistency check, but it is less diagnostic than the learned-hand matrix because it does not expose strategy-dependent failures. This motivates the use of league-trained virtual patients as a stress-test distribution for adaptive rehabilitation policies.':
    'The sorted empirical matrix gives a complementary view of this trend. Early robot generations perform well only against a limited portion of the hand pool, whereas later generations maintain useful ZPD interaction across a broader range of opponent difficulty. The scripted-hand evaluation remains useful as a consistency check, but it is less diagnostic than the learned-hand matrix because it does not expose strategy-dependent failures. This motivates league-trained virtual patients as a stress-test distribution for adaptive rehabilitation policies.',

    'Fig. 2 summarizes the ablation result. The most prominent change occurs when temporal interaction history is introduced: both recurrent policies learn longer and more rewarding interactions than the MLP baseline. This indicates that the controller benefits from observing how the hand has been moving, not only where the hand is at the current instant. In contrast, the auxiliary variant follows a trajectory close to the GRU-only policy in the aggregate training curves. This suggests that, under the current training setting, temporal sequence modeling is the dominant contributor to control performance, while the auxiliary objective mainly shapes the learned representation.':
    'Fig. 2 summarizes the ablation. The main improvement occurs when temporal interaction history is introduced: both recurrent policies learn longer and more rewarding interactions than the MLP baseline. This indicates that the controller benefits from observing how the hand has been moving, not only where it is at the current instant. The auxiliary variant follows a trajectory close to the GRU-only policy in the aggregate training curves, suggesting that temporal sequence modeling is the dominant contributor to control performance in this setting, while the auxiliary objective primarily shapes the representation.',

    'The auxiliary prediction results provide additional insight into what the temporal representation has learned. Even when the policy-level improvement is modest, the future-dynamics head exposes what the temporal representation has learned about hand motion. The predicted trajectories capture short-horizon movement direction and progressively diverge at longer horizons, which is consistent with the uncertainty of multi-step forecasting in an interactive task. In this run, the auxiliary task does not function as an independent performance booster. Instead, it serves as a mechanism for encouraging and diagnosing patient-dynamics representation.':
    'The auxiliary prediction results clarify what the temporal representation has learned. The predicted trajectories capture short-horizon movement direction and progressively diverge at longer horizons, consistent with the uncertainty of multi-step forecasting in an interactive task. In this run, the auxiliary task does not act as an independent source of policy improvement. Instead, it encourages and diagnoses patient-dynamics representation.',

    'The final comparison evaluates whether the learned robot behavior transfers across different hand-control mechanisms. The scripted controller represents a simple noisy pursuit strategy, whereas the learned hand agent can exploit interaction patterns acquired through RL training. A robust rehabilitation controller should not be tuned exclusively to either case; it should maintain useful interaction when the hand behavior shifts between rule-based pursuit and learned strategic pursuit.':
    'The final comparison evaluates whether the learned robot behavior transfers across hand-control mechanisms. The scripted controller represents noisy rule-based pursuit, whereas the learned hand agent can exploit interaction patterns acquired through RL training. A robust rehabilitation controller should not be tuned exclusively to either case; it should maintain useful interaction as hand behavior shifts between rule-based and learned pursuit.',

    'Table II uses the format TIS / ZPD coverage / episode length / catch rate. The scripted-only baseline behaves as expected: it remains relatively effective on the scripted hand but is frequently caught by the learned agent. The single-agent baseline shows the opposite pattern, performing well against the learned hand while degrading on the scripted controller. These complementary failures indicate that training against a single opponent type can produce brittle specialization. The league-trained robot avoids the strongest form of either failure mode and provides the most balanced behavior across the two automated test conditions. Mouse-controlled human-in-the-loop evaluation is treated as a separate validation stage.':
    'Table II reports TIS, ZPD coverage, episode length, and catch rate. The scripted-only baseline remains relatively effective on the scripted hand but is frequently caught by the learned agent. The single-agent baseline shows the opposite pattern, performing well against the learned hand while degrading on the scripted controller. These complementary failures indicate that training against a single opponent type can produce brittle specialization. The league-trained robot avoids the strongest form of either failure mode and provides the most balanced behavior across the two automated test conditions. Mouse-controlled human-in-the-loop evaluation is treated as a separate validation stage.',

    'Sim-to-real transfer in this system involves multiple compounding gaps: real hand kinematics, camera latency, and magnetic actuation dynamics are all absent from the virtual training environment. We therefore treat physical deployment as a closed-loop feasibility study rather than a paired benchmark comparison. The implementation uses the same 44-dimensional observation structure as simulation: robot position from Real-Time Data Exchange (RTDE), hand and microrobot positions from the overhead camera, boundary features, previous action, and the displacement-history buffer.':
    'Sim-to-real transfer in this system involves several compounding gaps. Real hand kinematics, camera latency, and magnetic actuation dynamics are not fully represented in the virtual training environment. We therefore treat physical deployment as a closed-loop feasibility study rather than a paired benchmark comparison. The implementation uses the same 44-dimensional observation structure as simulation: robot position from Real-Time Data Exchange (RTDE), hand and microrobot positions from the overhead camera, boundary features, previous action, and the displacement-history buffer.',

    'Perception and control run in separate threads to avoid jitter. The camera runs at 10-15 Hz, whereas the robot requires deterministic commands at a fixed control rate. Running both processes in one thread would allow a slow You Only Look Once (YOLO) inference step to stall the control loop. We therefore use two threads connected by a single-element message queue. The vision thread captures frames, runs undistortion and detection, and pushes results to the queue. If the queue is full, the stale result is replaced. The control thread runs at 20 Hz and attempts a non-blocking read each cycle. If a new frame is available, the hand position is updated; otherwise the system falls back to dead reckoning using a low-pass filtered velocity estimate from recent vision updates.':
    'Perception and control run in separate threads to avoid jitter. The camera runs at 10-15 Hz, whereas the robot requires deterministic commands at a fixed control rate. If both processes ran in one thread, a slow You Only Look Once (YOLO) inference step could stall the control loop. The system therefore uses two threads connected by a single-element message queue. The vision thread captures frames, runs undistortion and detection, and pushes results to the queue. If the queue is full, stale results are replaced. The control thread runs at 20 Hz and attempts a non-blocking read each cycle. If a new frame is available, the hand position is updated; otherwise, the system uses dead reckoning based on a low-pass filtered velocity estimate from recent vision updates.',

    'The 44-dimensional observation is assembled from the estimated hand position, the robot position via RTDE, and the displacement-history buffer, then fed to the PPO policy. The 2D action is accumulated as a virtual target in pixel space, rate-limited to prevent large per-step motion, and mapped to world coordinates via the inverse homography. The final pose is sent to the UR10 through the servoL interface with a 0.1 s lookahead time and proportional gain of 400, yielding smooth end-effector tracking.':
    'The 44-dimensional observation is assembled from the estimated hand position, the robot position obtained through RTDE, and the displacement-history buffer. The observation is then passed to the PPO policy. The resulting two-dimensional action is accumulated as a virtual target in pixel space, rate-limited to prevent abrupt per-step motion, and mapped to world coordinates through the inverse homography. The final pose is sent to the UR10 through the servoL interface with a 0.1-s lookahead time and a proportional gain of 400, yielding smooth end-effector tracking.'
}

for p in doc.paragraphs:
    text = p.text.strip()
    if text in replacements:
        p.text = replacements[text]

doc.save(out)
print(out.as_posix())
