# 摄像头配置
camera_id: 0                        # 摄像头ID
desired_width: 2592                 # 期望宽度
desired_height: 1944                # 期望高度

# 相机标定文件路径（相对于deployment目录）
calibration_matrix_path: "./vision/calibration_data.npz"
homography_matrix_path: "./vision/Homography_matrix.npy"

# 工作空间配置
workspace_crop: [600, -400]         # 工作空间裁剪 [left, right]，负数表示从右边裁剪

